let data = [

  {
    num: '1',
    name: 'Big sphere with a picture',
    count: '2',
    year: '1960',
    shape: 'sphere',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '2',
    name: 'Green sphere with flowers',
    count: '5',
    year: '2000',
    shape: 'sphere',
    color: 'green',
    size: 'big',
    favorite: false,
  },
  {
    num: '3',
    name: 'Red matt sphere',
    count: '3',
    year: '1990',
    shape: 'sphere',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '4',
    name: 'Red icicle',
    count: '2',
    year: '1980',
    shape: 'figure',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '5',
    name: 'Red grape',
    count: '4',
    year: '1980',
    shape: 'figure',
    color: 'red',
    size: 'middle',
    favorite: true,
  },
  {
    num: '6',
    name: 'Red sphere with a picture',
    count: '6',
    year: '2010',
    shape: 'sphere',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '7',
    name: 'Milky white sphere',
    count: '12',
    year: '1960',
    shape: 'sphere',
    color: 'white',
    size: 'middle',
    favorite: true,
  },
  {
    num: '8',
    name: 'Red sphere',
    count: '10',
    year: '2010',
    shape: 'sphere',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '9',
    name: 'Old bell',
    count: '2',
    year: '1950',
    shape: 'bell',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '10',
    name: 'White sphere retro',
    count: '7',
    year: '1960',
    shape: 'sphere',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '11',
    name: 'White cone',
    count: '11',
    year: '1960',
    shape: 'cone',
    color: 'white',
    size: 'small',
    favorite: false,
  },
  {
    num: '12',
    name: 'White sphere with flowers',
    count: '5',
    year: '1980',
    shape: 'sphere',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '13',
    name: 'Sphere with a river',
    count: '3',
    year: '1970',
    shape: 'sphere',
    color: 'blue',
    size: 'big',
    favorite: true,
  },
  {
    num: '14',
    name: 'Sphere with a village',
    count: '4',
    year: '1970',
    shape: 'sphere',
    color: 'blue',
    size: 'big',
    favorite: true,
  },
  {
    num: '15',
    name: 'Bell colored',
    count: '3',
    year: '1970',
    shape: 'bell',
    color: 'blue',
    size: 'middle',
    favorite: false,
  },
  {
    num: '16',
    name: 'Cone with a scenery',
    count: '3',
    year: '1970',
    shape: 'cone',
    color: 'blue',
    size: 'middle',
    favorite: true,
  },
  {
    num: '17',
    name: 'Cone colored',
    count: '7',
    year: '1970',
    shape: 'cone',
    color: 'red',
    size: 'middle',
    favorite: false,
  },
  {
    num: '18',
    name: 'Yellow sphere with a bow',
    count: '2',
    year: '2010',
    shape: 'sphere',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '19',
    name: 'Yellow sphere with glitter',
    count: '12',
    year: '1980',
    shape: 'sphere',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '20',
    name: 'Red sphere with a bow',
    count: '8',
    year: '1950',
    shape: 'sphere',
    color: 'red',
    size: 'middle',
    favorite: true,
  },
  {
    num: '21',
    name: 'Red sphere with stars',
    count: '4',
    year: '1970',
    shape: 'sphere',
    color: 'red',
    size: 'big',
    favorite: true,
  },
  {
    num: '22',
    name: 'Golden cone',
    count: '11',
    year: '1990',
    shape: 'cone',
    color: 'yellow',
    size: 'small',
    favorite: false,
  },
  {
    num: '23',
    name: 'Old bell',
    count: '9',
    year: '1950',
    shape: 'bell',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '24',
    name: 'Elegant snowflake',
    count: '1',
    year: '1940',
    shape: 'snowflake',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '25',
    name: 'Pink sphere with glitter',
    count: '12',
    year: '2010',
    shape: 'sphere',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '26',
    name: 'Ruby gold sphere',
    count: '8',
    year: '1960',
    shape: 'sphere',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '27',
    name: 'Red sphere with pattern',
    count: '4',
    year: '2010',
    shape: 'sphere',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '28',
    name: 'Red sphere with pattern',
    count: '10',
    year: '2010',
    shape: 'sphere',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '29',
    name: 'Old sphere with flowers',
    count: '5',
    year: '1950',
    shape: 'sphere',
    color: 'yellow',
    size: 'big',
    favorite: true,
  },
  {
    num: '30',
    name: 'Old sphere with pattern',
    count: '8',
    year: '1950',
    shape: 'sphere',
    color: 'yellow',
    size: 'big',
    favorite: true,
  },
  {
    num: '31',
    name: 'Red sphere with glitter',
    count: '8',
    year: '2010',
    shape: 'sphere',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '32',
    name: 'Blue sphere Universe',
    count: '11',
    year: '1970',
    shape: 'sphere',
    color: 'blue',
    size: 'big',
    favorite: false,
  },
  {
    num: '33',
    name: 'Blue sphere with a snowflake',
    count: '6',
    year: '2010',
    shape: 'sphere',
    color: 'blue',
    size: 'middle',
    favorite: false,
  },
  {
    num: '34',
    name: 'Green  sphere with pattern',
    count: '8',
    year: '2010',
    shape: 'sphere',
    color: 'green',
    size: 'big',
    favorite: false,
  },
  {
    num: '35',
    name: 'Fox figure in a sphere',
    count: '8',
    year: '1950',
    shape: 'figure',
    color: 'yellow',
    size: 'middle',
    favorite: true,
  },
  {
    num: '36',
    name: 'Pink sphere',
    count: '1',
    year: '2000',
    shape: 'sphere',
    color: 'blue',
    size: 'big',
    favorite: false,
  },
  {
    num: '37',
    name: 'Green  sphere',
    count: '6',
    year: '2000',
    shape: 'sphere',
    color: 'green',
    size: 'big',
    favorite: false,
  },
  {
    num: '38',
    name: 'Light blue sphere',
    count: '6',
    year: '2000',
    shape: 'sphere',
    color: 'blue',
    size: 'big',
    favorite: false,
  },
  {
    num: '39',
    name: 'Red snowflake',
    count: '6',
    year: '1990',
    shape: 'snowflake',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '40',
    name: 'Golden snowflake',
    count: '12',
    year: '2020',
    shape: 'snowflake',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '41',
    name: 'Arctic snowflake',
    count: '11',
    year: '2020',
    shape: 'snowflake',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '42',
    name: 'Green sphere',
    count: '10',
    year: '1980',
    shape: 'sphere',
    color: 'green',
    size: 'middle',
    favorite: false,
  },
  {
    num: '43',
    name: 'Two-colored snowflake',
    count: '6',
    year: '1960',
    shape: 'snowflake',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '44',
    name: 'Angel figure',
    count: '11',
    year: '1940',
    shape: 'figure',
    color: 'red',
    size: 'middle',
    favorite: true,
  },
  {
    num: '45',
    name: 'New Years Snowflake',
    count: '1',
    year: '1980',
    shape: 'snowflake',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '46',
    name: 'Figure Amanita',
    count: '10',
    year: '1950',
    shape: 'figure',
    color: 'red',
    size: 'small',
    favorite: false,
  },
  {
    num: '47',
    name: 'Figure Well',
    count: '6',
    year: '1950',
    shape: 'figure',
    color: 'red',
    size: 'small',
    favorite: false,
  },
  {
    num: '48',
    name: 'Yellow sphere with a bow',
    count: '6',
    year: '1960',
    shape: 'sphere',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '49',
    name: 'Snowflake with turquoise',
    count: '4',
    year: '1980',
    shape: 'snowflake',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '50',
    name: 'Big bell',
    count: '3',
    year: '2020',
    shape: 'bell',
    color: 'red',
    size: 'big',
    favorite: false,
  },
  {
    num: '51',
    name: 'Cone with frost',
    count: '12',
    year: '1970',
    shape: 'cone',
    color: 'red',
    size: 'small',
    favorite: false,
  },
  {
    num: '52',
    name: 'Red sphere with text',
    count: '12',
    year: '1990',
    shape: 'sphere',
    color: 'red',
    size: 'big',
    favorite: true,
  },
  {
    num: '53',
    name: 'Silver snowflake',
    count: '6',
    year: '2020',
    shape: 'snowflake',
    color: 'white',
    size: 'big',
    favorite: false,
  },
  {
    num: '54',
    name: 'Green sphere with a picture',
    count: '6',
    year: '2010',
    shape: 'sphere',
    color: 'green',
    size: 'big',
    favorite: false,
  },
  {
    num: '55',
    name: 'Gingerbread house',
    count: '1',
    year: '1940',
    shape: 'figure',
    color: 'yellow',
    size: 'big',
    favorite: false,
  },
  {
    num: '56',
    name: 'Gingerbread house',
    count: '1',
    year: '1940',
    shape: 'figure',
    color: 'yellow',
    size: 'small',
    favorite: false,
  },
  {
    num: '57',
    name: 'Gingerbread house',
    count: '1',
    year: '1940',
    shape: 'figure',
    color: 'yellow',
    size: 'middle',
    favorite: false,
  },
  {
    num: '58',
    name: 'Polar Bear figure',
    count: '2',
    year: '1980',
    shape: 'figure',
    color: 'white',
    size: 'middle',
    favorite: false,
  },
  {
    num: '59',
    name: 'Yellow sphere with text',
    count: '10',
    year: '1990',
    shape: 'sphere',
    color: 'yellow',
    size: 'middle',
    favorite: false,
  },
  {
    num: '60',
    name: 'Pigeon figure',
    count: '12',
    year: '1940',
    shape: 'figure',
    color: 'white',
    size: 'middle',
    favorite: true,
  },
];

export default data;